"""added catalogues table

Revision ID: d32dbfbba6e6
Revises: a65f9e2e78e8
Create Date: 2025-12-05 15:07:42.952610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd32dbfbba6e6'
down_revision: Union[str, None] = 'a65f9e2e78e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
